version: '3'

services:
  smtp:
    build: .
    ports:
      - "25:25"
      - "465:465"
    env_file:
      - ./.env
    volumes:
      - "./custom:/var/smtp-logger/custom"
      - "logs:/var/smtp-logger/storage/logs"
      - "mail:/var/smtp-logger/storage/mail"

volumes:
  logs:
  mail:
